# Docs: https://docs.cortex.io/docs/reference/basics/entities#service-entities

openapi: 3.0.0
info:
  title: plumber
  description: >
    A collection of libraries that are useful for implementing Go services, libraries, and more.
  x-cortex-type: service
  x-cortex-slack:
    channels:
      - name: ecs-team
        notificationsEnabled: false
  x-cortex-owners:
    - type: group
      name: ce-ecs
      provider: CORTEX
  x-cortex-tag: plumber
  x-cortex-git:
    github:
      repository: getoutreach/plumber
  x-cortex-oncall:
    pagerduty:
      id: PKQG42T
      type: SERVICE
  x-cortex-link:
    ## These are useful documentation links for this service. Please fill in the customLinks block if you have additional documentation links.
    ## name: The name of the link
    ## type: Choose one type from (dashboard,documentation,healthcheck,logs,metrics,runbook)
    ## url: The link url
    ## description(optional): Description to this link
    - name: API Docs
      type: api_documentation
      url: https://engdocs.outreach.cloud/github.com/getoutreach/plumber#section-readme
    ## <<Stencil::Block(customLinks)>>
    ## <</Stencil::Block>>
  x-cortex-custom-metadata:
    app: plumber
    name: plumber
    repo: https://github.com/getoutreach/plumber
    framework: stencil
    language: Golang
    stencil_version: v1.38.0
    golang_version: 1.22.0
    cli: false
    service: false
    product: Outreach
    lifecycle: in_development
    ## <<Stencil::Block(extraAliases)>>
    ## <</Stencil::Block>>
    reporting_team: ce-ecs
    lintroller: platinum
  x-cortex-groups:
    - lifecycle: in_development
    - product: Outreach
    - language: Golang
    - framework: stencil
    - engOrg: ce
